<?php

/**
* Export to PHP Array plugin for PHPMyAdmin
* @version 0.2b
*/

//
// Database `sparcu_whmc595`
//

// `sparcu_whmc595`.`tblproductgroups`
$tblproductgroups = array(
array('id' => '2','name' => 'Reseller Hosting (US Asia Europe)','headline' => 'RESELLER HOSTING','tagline' => 'Make Money By Hosting Your Own Clients!','orderfrmtpl' => 'standard_cart','disabledgateways' => 'mailin','hidden' => '0','order' => '3','created_at' => '2017-01-19 07:10:21','updated_at' => '2017-01-27 06:39:06'),
array('id' => '3','name' => 'VPS Hosting (US Asia Europe)','headline' => '','tagline' => 'Outgrown Shared hosting? Try aVPS','orderfrmtpl' => 'standard_cart','disabledgateways' => 'mailin','hidden' => '0','order' => '2','created_at' => '2017-01-19 07:12:18','updated_at' => '2017-01-27 06:39:06'),
array('id' => '4','name' => 'Dedicated Servers (USA)','headline' => 'USA DEDICATED SERVERS','tagline' => 'Dedicated Servers for Ultimate Performance and Control','orderfrmtpl' => 'standard_cart','disabledgateways' => 'mailin','hidden' => '0','order' => '4','created_at' => '2017-01-19 07:18:01','updated_at' => '2017-01-27 06:39:06'),
array('id' => '5','name' => 'Web Hosting (Multiple Locations)','headline' => 'POWERFUL WEB HOSTING','tagline' => 'High Performance Web Hosting Made EASY and AFFORDABLE!','orderfrmtpl' => '','disabledgateways' => 'mailin','hidden' => '0','order' => '1','created_at' => '2017-01-20 03:16:08','updated_at' => '2017-01-27 06:39:06')
);

/**
* Export to PHP Array plugin for PHPMyAdmin
* @version 0.2b
*/

//
// Database `sparcu_whmc595`
//

// `sparcu_whmc595`.`tblpricing`
$tblpricing = array(
array('id' => '22','type' => 'product','currency' => '1','relid' => '7','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '1.95','quarterly' => '5.85','semiannually' => '11.70','annually' => '14.95','biennially' => '46.80','triennially' => '70.20'),
array('id' => '23','type' => 'product','currency' => '1','relid' => '8','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '2.45','quarterly' => '7.35','semiannually' => '14.70','annually' => '19.40','biennially' => '58.80','triennially' => '88.20'),
array('id' => '24','type' => 'product','currency' => '1','relid' => '9','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '3.95','quarterly' => '11.85','semiannually' => '23.70','annually' => '29.95','biennially' => '94.80','triennially' => '142.20'),
array('id' => '31','type' => 'configoptions','currency' => '1','relid' => '7','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '1.00','quarterly' => '0.00','semiannually' => '0.00','annually' => '0.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '32','type' => 'configoptions','currency' => '1','relid' => '8','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '1.00','quarterly' => '0.00','semiannually' => '0.00','annually' => '0.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '33','type' => 'configoptions','currency' => '1','relid' => '9','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '1.00','quarterly' => '0.00','semiannually' => '0.00','annually' => '0.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '116','type' => 'product','currency' => '1','relid' => '61','msetupfee' => '25.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '89.95','quarterly' => '-1.00','semiannually' => '-1.00','annually' => '-1.00','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '137','type' => 'product','currency' => '1','relid' => '62','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '9.95','quarterly' => '29.85','semiannually' => '59.70','annually' => '119.40','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '138','type' => 'product','currency' => '1','relid' => '63','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '16.95','quarterly' => '50.85','semiannually' => '101.70','annually' => '203.40','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '139','type' => 'product','currency' => '1','relid' => '64','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '19.95','quarterly' => '59.85','semiannually' => '119.70','annually' => '239.40','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '140','type' => 'product','currency' => '1','relid' => '65','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '24.95','quarterly' => '74.85','semiannually' => '149.70','annually' => '299.40','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '141','type' => 'product','currency' => '1','relid' => '66','msetupfee' => '25.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '99.95','quarterly' => '-1.00','semiannually' => '-1.00','annually' => '-1.00','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '142','type' => 'configoptions','currency' => '1','relid' => '61','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '0.00','quarterly' => '0.00','semiannually' => '0.00','annually' => '0.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '143','type' => 'configoptions','currency' => '1','relid' => '62','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '20.00','quarterly' => '60.00','semiannually' => '120.00','annually' => '240.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '144','type' => 'configoptions','currency' => '1','relid' => '63','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '25.00','quarterly' => '75.00','semiannually' => '150.00','annually' => '300.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '145','type' => 'configoptions','currency' => '1','relid' => '64','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '40.00','quarterly' => '120.00','semiannually' => '240.00','annually' => '480.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '146','type' => 'configoptions','currency' => '1','relid' => '65','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '0.00','quarterly' => '0.00','semiannually' => '0.00','annually' => '0.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '147','type' => 'configoptions','currency' => '1','relid' => '66','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '0.00','quarterly' => '0.00','semiannually' => '0.00','annually' => '0.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '148','type' => 'configoptions','currency' => '1','relid' => '67','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '15.00','quarterly' => '45.00','semiannually' => '90.00','annually' => '180.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '149','type' => 'configoptions','currency' => '1','relid' => '68','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '25.00','quarterly' => '75.00','semiannually' => '150.00','annually' => '300.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '150','type' => 'configoptions','currency' => '1','relid' => '69','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '40.00','quarterly' => '120.00','semiannually' => '240.00','annually' => '480.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '151','type' => 'configoptions','currency' => '1','relid' => '70','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '40.00','quarterly' => '120.00','semiannually' => '240.00','annually' => '480.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '152','type' => 'configoptions','currency' => '1','relid' => '71','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '50.00','quarterly' => '150.00','semiannually' => '300.00','annually' => '600.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '154','type' => 'configoptions','currency' => '1','relid' => '73','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '50.00','quarterly' => '150.00','semiannually' => '300.00','annually' => '600.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '155','type' => 'configoptions','currency' => '1','relid' => '74','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '0.00','quarterly' => '0.00','semiannually' => '0.00','annually' => '0.00','biennially' => '0.00','triennially' => '0.00'),
array('id' => '160','type' => 'product','currency' => '1','relid' => '67','msetupfee' => '25.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '119.95','quarterly' => '-1.00','semiannually' => '-1.00','annually' => '-1.00','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '161','type' => 'product','currency' => '1','relid' => '68','msetupfee' => '25.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '219.95','quarterly' => '-1.00','semiannually' => '-1.00','annually' => '-1.00','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '180','type' => 'product','currency' => '1','relid' => '69','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '15.00','quarterly' => '45.00','semiannually' => '-1.00','annually' => '-1.00','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '186','type' => 'product','currency' => '1','relid' => '70','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '1.25','quarterly' => '3.75','semiannually' => '7.50','annually' => '9.95','biennially' => '14.95','triennially' => '22.95'),
array('id' => '187','type' => 'product','currency' => '1','relid' => '71','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '80.00','quarterly' => '240.00','semiannually' => '-1.00','annually' => '-1.00','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '189','type' => 'product','currency' => '1','relid' => '73','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '30.00','quarterly' => '90.00','semiannually' => '-1.00','annually' => '-1.00','biennially' => '-1.00','triennially' => '-1.00'),
array('id' => '190','type' => 'product','currency' => '1','relid' => '74','msetupfee' => '0.00','qsetupfee' => '0.00','ssetupfee' => '0.00','asetupfee' => '0.00','bsetupfee' => '0.00','tsetupfee' => '0.00','monthly' => '120.00','quarterly' => '360.00','semiannually' => '-1.00','annually' => '-1.00','biennially' => '-1.00','triennially' => '-1.00')
);

/**
* Export to PHP Array plugin for PHPMyAdmin
* @version 0.2b
*/

//
// Database `sparcu_whmc595`
//

// `sparcu_whmc595`.`tblproducts`
$tblproducts = array(
array('id' => '7','type' => 'hostingaccount','gid' => '5','name' => 'Shared Hosting Deluxe Plan','description' => '5GB SSD RAID 10 Storage
500GB Bandwidth
5 Hosted Domain
Unlimited Email Accounts
Unlimited Databases
CloudFlare CDN
Website Site Builder
Softaculous Auto Script Installer','hidden' => '0','showdomainoptions' => '1','welcomeemail' => '1','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '1','retired' => '0','is_featured' => '0','created_at' => '2017-01-19 07:46:46','updated_at' => '2017-01-27 04:47:57'),
array('id' => '8','type' => 'hostingaccount','gid' => '5','name' => 'Shared Hosting Business Plan','description' => '10GB SSD RAID 10 Storage
1000GB Bandwidth
10 Hosted Domains
<strong>MailChannels Business Email</strong>
Unlimited Email Accounts
Unlimited Databases
CloudFlare CDN
Site Builder & Auto Script Installer','hidden' => '0','showdomainoptions' => '1','welcomeemail' => '1','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '2','retired' => '0','is_featured' => '0','created_at' => '2017-01-19 07:46:46','updated_at' => '2017-01-27 04:48:12'),
array('id' => '9','type' => 'hostingaccount','gid' => '5','name' => 'Shared Hosting Enterprise Plan','description' => '25GB SSD RAID 10 Storage
Unlimited Bandwidth
Unlimited Hosted Domains
MailChannels Business Email
Unlimited Email and Databases
CloudFlare CDN
Site Builder & Auto Script Installer
<strong>Attracta’s Powerful SEO Tools</strong>','hidden' => '0','showdomainoptions' => '1','welcomeemail' => '1','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '3','retired' => '0','is_featured' => '0','created_at' => '2017-01-19 07:46:46','updated_at' => '2017-01-29 07:59:58'),
array('id' => '61','type' => 'server','gid' => '4','name' => 'Dual Intel Xeon Quad Core 5420 - 8 CPU','description' => '16GB RAM
500GB SATA Hard Drive
1Gbps Uplink
10,000GB US Premium Bandwidth
4 Usable IP\'s
Linux Operating System','hidden' => '0','showdomainoptions' => '0','welcomeemail' => '17','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-22 11:26:28','updated_at' => '2017-01-24 06:20:46'),
array('id' => '62','type' => 'reselleraccount','gid' => '2','name' => 'USA Budget Reseller 01','description' => '100GB Pure SSD Storage
100 cPanel Accounts
1TB Premium USA Bandwidth
Softaculous Auto Script Installer
Unli. Email. MySQL. Domains Etc.
300% Faster with SSD
Host Multiple cPanel Accounts
WHM Reseller Management Panel
Free Assistance to Get Started','hidden' => '0','showdomainoptions' => '1','welcomeemail' => '0','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => 'cpanel','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-22 14:24:44','updated_at' => '2017-01-22 14:47:49'),
array('id' => '63','type' => 'reselleraccount','gid' => '2','name' => 'USA Budget Reseller 02','description' => '200GB Pure SSD Storage
200 cPanel Accounts
2TB Premium USA Bandwidth
Softaculous Auto Script Installer
Unli. Email. MySQL. Domains Etc.
300% Faster with SSD
Host Multiple cPanel Accounts
WHM Reseller Management Panel
Free Assistance to Get Started','hidden' => '0','showdomainoptions' => '1','welcomeemail' => '0','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => 'cpanel','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-22 14:24:44','updated_at' => '2017-01-22 14:46:36'),
array('id' => '64','type' => 'reselleraccount','gid' => '2','name' => 'USA Budget Reseller 03','description' => '300GB Pure SSD Storage
300 cPanel Accounts
3TB Premium USA Bandwidth
Softaculous Auto Script Installer
Unli. Email. MySQL. Domains Etc.
300% Faster with SSD
Host Multiple cPanel Accounts
WHM Reseller Management Panel
Free Assistance to Get Started','hidden' => '0','showdomainoptions' => '1','welcomeemail' => '0','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => 'cpanel','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-22 14:24:44','updated_at' => '2017-01-22 14:46:15'),
array('id' => '65','type' => 'reselleraccount','gid' => '2','name' => 'USA Budget Reseller 04','description' => 'Unlimited Pure SSD Storage
Unlimited cPanel Accounts
Unlimited Premium USA Bandwidth
Softaculous Auto Script Installer
Unli. Email. MySQL. Domains Etc.
300% Faster with SSD
Host Multiple cPanel Accounts
WHM Reseller Management Panel
Free Assistance to Get Started','hidden' => '0','showdomainoptions' => '1','welcomeemail' => '0','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => 'cpanel','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-22 14:24:44','updated_at' => '2017-01-22 14:45:51'),
array('id' => '66','type' => 'server','gid' => '4','name' => 'Intel Dual Xeon L5520 (16CPU - 48GB)','description' => '<strong>48GB RAM</strong>
<strong>1TB</strong> SATA Hard Drive
1Gbps Uplink
10,000GB US Premium Bandwidth
4 Usable IP\'s
Linux Operating System','hidden' => '0','showdomainoptions' => '0','welcomeemail' => '17','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '1','retired' => '0','is_featured' => '0','created_at' => '2017-01-22 11:26:28','updated_at' => '2017-01-25 05:04:09'),
array('id' => '67','type' => 'server','gid' => '4','name' => 'Intel Dual Xeon L5520 (16CPU - 72GB)','description' => '<strong>72GB RAM</strong>
<strong>1TB</strong> SATA Hard Drive
1Gbps Uplink
10,000GB US Premium Bandwidth
4 Usable IP\'s
Linux Operating System','hidden' => '0','showdomainoptions' => '0','welcomeemail' => '17','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '2','retired' => '0','is_featured' => '0','created_at' => '2017-01-22 11:26:28','updated_at' => '2017-01-25 05:04:09'),
array('id' => '68','type' => 'server','gid' => '4','name' => 'Dual Xeon E5-2650 32CPU 64GB 1TB SSD','description' => '64GB RAM
<strong>1TB SSD Drive</strong>
1Gbps Uplink
10,000GB US Premium Bandwidth
4 Usable IP\'s
Linux Operating System','hidden' => '0','showdomainoptions' => '0','welcomeemail' => '17','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '3','retired' => '0','is_featured' => '0','created_at' => '2017-01-22 11:26:28','updated_at' => '2017-01-25 05:12:14'),
array('id' => '69','type' => 'server','gid' => '3','name' => 'Linux SSD VPS 01','description' => '1 High Performance CPU
2GB - 8GB RAM (Configurable)
50GB Space (100% SSD)
500 GB Bandwidth
Linux Operating System
WHM/cPanel (Optional)
Fully Managed / Self Managed','hidden' => '0','showdomainoptions' => '0','welcomeemail' => '0','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-25 14:21:37','updated_at' => '2017-01-26 12:51:16'),
array('id' => '70','type' => 'hostingaccount','gid' => '5','name' => 'Shared Hosting Budget Plan','description' => '2GB SSD RAID 10 Storage
200GB Bandwidth
1 Hosted Domain
Unlimited Email Accounts
Unlimited Databases
CloudFlare CDN
Site Builder & Auto Script Installer
Softaculous Auto Script Installer','hidden' => '0','showdomainoptions' => '1','welcomeemail' => '1','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-19 07:46:46','updated_at' => '2017-01-27 04:47:43'),
array('id' => '71','type' => 'server','gid' => '3','name' => 'Linux SSD VPS 03','description' => '4 High Performance CPU\'s
16GB - 24GB RAM (Configurable)
150GB Space (100% SSD)
1500 GB Bandwidth
Linux Operating System
WHM/cPanel (Optional)
Fully Managed / Self Managed','hidden' => '0','showdomainoptions' => '0','welcomeemail' => '0','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-25 14:21:37','updated_at' => '2017-01-26 13:51:07'),
array('id' => '73','type' => 'server','gid' => '3','name' => 'Linux SSD VPS 02','description' => '2 High Performance CPU\'s
4GB - 16GB RAM (Configurable)
100GB Space (100% SSD)
1000GB Bandwidth
Linux Operating System
WHM/cPanel (Optional)
Fully Managed / Self Managed','hidden' => '0','showdomainoptions' => '0','welcomeemail' => '0','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-25 14:21:37','updated_at' => '2017-01-26 13:01:28'),
array('id' => '74','type' => 'server','gid' => '3','name' => 'Linux SSD VPS 04','description' => '6 High Performance CPU\'s
24GB - 32GB RAM (Configurable)
300GB Space (100% SSD)
3000 GB Bandwidth
Linux Operating System
WHM/cPanel (Optional)
Fully Managed / Self Managed','hidden' => '0','showdomainoptions' => '0','welcomeemail' => '0','stockcontrol' => '0','qty' => '0','proratabilling' => '0','proratadate' => '0','proratachargenextmonth' => '0','paytype' => 'recurring','allowqty' => '0','subdomain' => '','autosetup' => '','servertype' => '','servergroup' => '0','configoption1' => '','configoption2' => '','configoption3' => '','configoption4' => '','configoption5' => '','configoption6' => '','configoption7' => '','configoption8' => '','configoption9' => '','configoption10' => '','configoption11' => '','configoption12' => '','configoption13' => '','configoption14' => '','configoption15' => '','configoption16' => '','configoption17' => '','configoption18' => '','configoption19' => '','configoption20' => '','configoption21' => '','configoption22' => '','configoption23' => '','configoption24' => '','freedomain' => '','freedomainpaymentterms' => '','freedomaintlds' => '','recurringcycles' => '0','autoterminatedays' => '0','autoterminateemail' => '0','configoptionsupgrade' => '0','billingcycleupgrade' => '','upgradeemail' => '0','overagesenabled' => '','overagesdisklimit' => '0','overagesbwlimit' => '0','overagesdiskprice' => '0.0000','overagesbwprice' => '0.0000','tax' => '0','affiliateonetime' => '0','affiliatepaytype' => '','affiliatepayamount' => '0.00','order' => '0','retired' => '0','is_featured' => '0','created_at' => '2017-01-25 14:21:37','updated_at' => '2017-01-26 13:52:19')
);
